# docker-compose.override.yml is used to override the docker-compose.yml file.

services:
  account-db:
    container_name: account-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=AccountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_account:/var/lib/postgresql/data
  
  likes-db:
    container_name: likes-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=LikeDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_likes:/var/lib/postgresql/data
  
  messages-db:
    container_name: messages-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MessageDb
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_messages:/var/lib/postgresql/data
  
  account.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=account-db;Port=5432;Database=AccountDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - account-db
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=account-db;Port=5432;Database=AccountDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - account-db
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  likes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=likes-db;Port=5432;Database=LikeDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - likes-db
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  messages.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=messages-db;Port=5432;Database=MessageDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - messages-db
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  bucket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=root007
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - account.api
      - user.api
      - likes.api
      - messages.api
      - bucket.api
    ports:
      - "7000:8080"
      - "7055:8081"
    volumes:
      - ~/.aspnet/https:/https:ro